baseURL: https://huija.github.io
languageCode: zh-cn
defaultContentLanguage: en
title: Huija's Blog
theme: cupper-hugo-theme
#googleAnalytics: UA-123456789-1
#disqusShortname: yourdiscussshortname
enableGitInfo: true
publishDir: docs

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: 欢迎扫码关注公众号, **从入门到删库跑路**！ <br/> ありがとうございました！ <br/>  ( •̀ ω •́ )✧
  homeMetaContent: Huija's Blog
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/huija/cupper-hugo-theme). Deployed to [Github Pages](https://github.com/huija/huija.github.io).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  moveFooterToHeader: false
  logoAlt: 佛祖保佑,永不BUG
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js
  utterances:
    owner: huija
    repo: huija.github.io
    issueTerm: title
    theme: github-light

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
